import React from 'react'
import Head from 'next/head'
import NavbarLogged from '../components/NavbarLogged'

const accueil = () => {
  return (
    
    <div>      
      <Head>
        <title>Influencer Business</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarLogged />
      <main>

      </main>
    </div>
  )
}

export default accueil