import Head from 'next/head'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Influencer Business</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div className='w-11/12 md:w-9/12 mx-auto flex justify-center items-center text-center font-bold text-xl md:text-2xl mt-96'>
          <h1 className='border-2 border-black rounded-md border-dashed px-8 py-4'>Veuillez vous connecter afin d'accéder à la plateforme</h1>
        </div>
      </main>
    </div>
  )
}
