import React, {useEffect} from 'react'
import Head from 'next/head'
import NavbarLogged from '../../../components/NavbarLogged'

function offres() {
  return (
    <div>      
      <Head>
        <title>Influencer Business</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarLogged />
      <main className='w-11/12 md:w-8/12 mt-10 lg:mt-20 mx-auto border border-black lg:pb-10 rounded-md'>
        <div className='mx-auto w-10/12'>
          <div className='flex items-center justify-between mt-10'>
            <h1 className='font-semibold text-xl lg:text-3xl'>Nouveau Projet</h1>
            <h2>Score actuel : <span className='font-bold text-blue-900'>260</span></h2>
          </div>
          <div className='flex flex-col lg:flex-row'>
            <div className='flex flex-col items-center mt-10'>
              <img src='https://res.cloudinary.com/devatchannel/image/upload/v1602752402/avatar/avatar_cugq40.png' className='w-32 bg-white' />
              <span className='border border-dashed border-black px-4 py-1 rounded-md mt-2 font-semibold'>Expert en dev</span>
              <h3 className='mt-10 font-semibold text-lg underline'>Description</h3>
              <p className='w-10/12 text-justify mt-2 max-w-[550px]'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Quisquam, quod. Quisquam, quod. Quisquam, quod. Quisquam, quod.
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Quisquam, quod. Quisquam, quod. Quisquam, quod. Quisquam, quod.
              </p>
            </div>
            <div className='flex pb-5 flex-col items-center border border-black rounded-sm max-w-[550px] w-10/12  lg:mr-10 mx-auto my-10'>
              <h2 className='mt-5'>Messages de : @expert en dev</h2>
              <p className='w-10/12 text-justify mt-10'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Quisquam, quod. Quisquam, quod. Quisquam, quod. Quisquam, quod.
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Quisquam, quod. Quisquam, quod. Quisquam, quod. Quisquam, quod.
              </p>
              <button className='bg-blue-900 text-white px-4 py-2 rounded-md mt-6'>Envoyer un message</button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}


export default offres